import type { Raw, Family } from "./types";

export const CLIMATES = [
  "temperate",
  "cold",
  "arctic",
  "steppe",
  "mediterranean",
  "tropical",
  "desert",
  "oceanic",
  "alpine",
  "subtropical",
  "savanna",
  "glacial",
  "hyperarid",
  "monsoon",
  "andean",
  "prairie",
  "mesoamerican",
] as const;
export type Climate = (typeof CLIMATES)[number];
export const BIOMES = [
  "woods",
  "forest",
  "hunting-forest",
  "golden-fields",
  "chernozem-wheat",
  "pasture",
  "rough-pasture",
  "clay",
  "gold",
  "iron",
  "stone",
  "coal",
  "salt-flats",
  "snow-plain",
  "seal-grounds",
  "arctic-iron",
  "arctic-stone",
  "arctic-gold",
  "steppe-plain",
  "olive-grove",
  "escarpment",
  "jungle",
  "tropical-woods",
  "rice-field",
  "desert",
  "oasis",
  "water",
  "fish",
  "cod",
  "whale",
  "ice",
  "coastal-pasture",
  "coastal-cliffs",
  "mountain-quarry",
  "alpine-pasture",
  "bare-peaks",
  "alluvial-clay",
  "river-woods",
  "wildlife-grassland",
  "dry-woodland",
  "barley-fields",
  "potato-fields",
  "turnip-fields",
  "oat-fields",
  "sorghum-fields",
  "alpaca-pasture",
  "sunflower-fields",
  "bison-range",
  "chinampa-gardens",
  "turkey-grounds",
  "cloud-forest",
  "volcanic-quarry",
  "millet-fields",
  "maize-field",
  "cattle-pasture",
  "goat-pasture",
  "reindeer-range",
  "cattle-savanna",
] as const;
export type Biome = (typeof BIOMES)[number];
export type TerrainResource =
  Raw | "water" | "snow" | "desert" | "ice" | "peaks";
export interface BiomeInfo {
  name: string;
  resource: TerrainResource;
  yield: Partial<Record<Raw, number>>;
  family: Family;
  art: string;
  color: string;
}
const b = (
  name: string,
  resource: TerrainResource,
  yield_: BiomeInfo["yield"],
  family: Family,
  art: string,
  color: string,
): BiomeInfo => ({ name, resource, yield: yield_, family, art, color });
export const BIOME_INFO: Record<Biome, BiomeInfo> = {
  "chernozem-wheat": b(
    "Black-soil wheat",
    "grain",
    { grain: 3 },
    "flat",
    "chernozem-wheat",
    "#a28c45",
  ),
  "barley-fields": b(
    "Barley fields",
    "grain",
    { grain: 1 },
    "flat",
    "barley-fields",
    "#cbb875",
  ),
  "potato-fields": b(
    "Potato fields",
    "grain",
    { grain: 2 },
    "flat",
    "potato-fields",
    "#a9ad66",
  ),
  "turnip-fields": b(
    "Turnip fields",
    "grain",
    { grain: 1 },
    "flat",
    "turnip-fields",
    "#a4aa75",
  ),
  "oat-fields": b(
    "Oat fields",
    "grain",
    { grain: 2 },
    "flat",
    "oat-fields",
    "#c5bc86",
  ),
  "sorghum-fields": b(
    "Sorghum fields",
    "grain",
    { grain: 2 },
    "flat",
    "sorghum-fields",
    "#b69067",
  ),
  "alpaca-pasture": b(
    "Alpaca pasture",
    "wool",
    { wool: 1, meat: 1 },
    "flat",
    "alpaca-pasture",
    "#a5a085",
  ),
  "sunflower-fields": b(
    "Sunflower fields",
    "oil",
    { oil: 1 },
    "flat",
    "sunflower-fields",
    "#ccad4f",
  ),
  "bison-range": b(
    "Bison range",
    "meat",
    { meat: 1, hides: 1 },
    "flat",
    "bison-range",
    "#ae936e",
  ),
  "chinampa-gardens": b(
    "Chinampa gardens",
    "grain",
    { grain: 3 },
    "flat",
    "chinampa-gardens",
    "#659768",
  ),
  "turkey-grounds": b(
    "Turkey grounds",
    "meat",
    { meat: 2 },
    "forest",
    "turkey-grounds",
    "#71816a",
  ),
  "cloud-forest": b(
    "Cloud forest",
    "lumber",
    { lumber: 1, hides: 1 },
    "forest",
    "cloud-forest",
    "#5c8c7d",
  ),
  "volcanic-quarry": b(
    "Volcanic quarry",
    "stone",
    { stone: 2 },
    "rugged",
    "volcanic-quarry",
    "#7c777d",
  ),
  "millet-fields": b(
    "Millet fields",
    "grain",
    { grain: 1 },
    "flat",
    "millet-fields",
    "#b99b58",
  ),
  "maize-field": b(
    "Maize fields",
    "grain",
    { grain: 2 },
    "flat",
    "maize-field",
    "#a8b851",
  ),
  "cattle-pasture": b(
    "Cattle pasture",
    "meat",
    { meat: 2 },
    "flat",
    "cattle-pasture",
    "#829c60",
  ),
  "goat-pasture": b(
    "Goat pasture",
    "meat",
    { meat: 1 },
    "rugged",
    "goat-pasture",
    "#aaa078",
  ),
  "reindeer-range": b(
    "Reindeer range",
    "meat",
    { meat: 1, hides: 1 },
    "flat",
    "reindeer-range",
    "#93a18b",
  ),
  "cattle-savanna": b(
    "Cattle range",
    "meat",
    { meat: 1, hides: 1 },
    "flat",
    "cattle-savanna",
    "#b7a468",
  ),
  woods: b("Woods", "lumber", { lumber: 1 }, "forest", "woods", "#7a9856"),
  forest: b("Forest", "lumber", { lumber: 2 }, "forest", "forest", "#355a48"),
  "hunting-forest": b(
    "Hunting forest",
    "hides",
    { hides: 2 },
    "forest",
    "hunting-forest",
    "#6c7960",
  ),
  "golden-fields": b(
    "Golden fields",
    "grain",
    { grain: 2 },
    "flat",
    "grain",
    "#d1ae50",
  ),
  pasture: b("Pasture", "wool", { wool: 2 }, "flat", "wool", "#95a66c"),
  "rough-pasture": b(
    "Rough pasture",
    "wool",
    { wool: 1 },
    "rugged",
    "rough-pasture",
    "#9d9b7e",
  ),
  clay: b("Clay hills", "brick", { brick: 1 }, "rugged", "brick", "#b16b50"),
  gold: b("Gold mountains", "gold", { gold: 1 }, "rugged", "gold", "#8f7544"),
  iron: b("Iron mountains", "ore", { ore: 1 }, "rugged", "ore", "#7d8293"),
  stone: b("Stone quarry", "stone", { stone: 1 }, "rugged", "stone", "#a6a49b"),
  coal: b("Coal hills", "coal", { coal: 1 }, "rugged", "coal", "#595c64"),
  "salt-flats": b("Salt flats", "salt", { salt: 1 }, "flat", "salt", "#dad5b9"),
  "snow-plain": b("Snow plain", "snow", {}, "flat", "snow-plain", "#dbe9e8"),
  "seal-grounds": b(
    "Seal hunting grounds",
    "hides",
    { hides: 1, oil: 1 },
    "flat",
    "seal-grounds",
    "#adc5c8",
  ),
  "arctic-iron": b(
    "Arctic iron mountains",
    "ore",
    { ore: 1 },
    "rugged",
    "arctic-iron",
    "#8596a9",
  ),
  "arctic-stone": b(
    "Arctic stone ridge",
    "stone",
    { stone: 1 },
    "rugged",
    "arctic-stone",
    "#b6c5ce",
  ),
  "arctic-gold": b(
    "Arctic gold mountains",
    "gold",
    { gold: 1 },
    "rugged",
    "arctic-gold",
    "#aaa07a",
  ),
  "steppe-plain": b(
    "Steppe plain",
    "hides",
    { hides: 1, wool: 1 },
    "flat",
    "steppe-plain",
    "#b0a272",
  ),
  "olive-grove": b(
    "Olive grove",
    "grain",
    { grain: 1 },
    "forest",
    "olive-grove",
    "#8e9860",
  ),
  escarpment: b(
    "Escarpment",
    "stone",
    { stone: 1 },
    "rugged",
    "escarpment",
    "#c5bba2",
  ),
  jungle: b("Jungle", "hides", { hides: 1 }, "forest", "jungle", "#416a49"),
  "tropical-woods": b(
    "Tropical woods",
    "lumber",
    { lumber: 1 },
    "forest",
    "tropical-woods",
    "#648753",
  ),
  "rice-field": b(
    "Rice field",
    "grain",
    { grain: 3 },
    "flat",
    "rice-field",
    "#91ac5b",
  ),
  desert: b("Desert", "desert", {}, "flat", "desert", "#d6b174"),
  oasis: b(
    "Oasis",
    "lumber",
    { lumber: 1, grain: 1 },
    "forest",
    "oasis",
    "#8f9f68",
  ),
  water: b("Water", "water", {}, "water", "water", "#287f9c"),
  fish: b("Fishing grounds", "water", { fish: 1 }, "water", "fish", "#287f9c"),
  cod: b("Cod grounds", "water", { fish: 2 }, "water", "cod", "#448a9d"),
  whale: b(
    "Whale grounds",
    "water",
    { hides: 1, oil: 1 },
    "water",
    "whale",
    "#287f9c",
  ),
  ice: b("Frozen sea", "ice", {}, "flat", "ice", "#aed7dc"),
  "coastal-pasture": b(
    "Coastal pasture",
    "wool",
    { wool: 2 },
    "flat",
    "oceanic-pasture",
    "#78a069",
  ),
  "coastal-cliffs": b(
    "Coastal cliffs",
    "stone",
    { stone: 1 },
    "rugged",
    "oceanic-stone",
    "#879b99",
  ),
  "mountain-quarry": b(
    "Mountain quarry",
    "stone",
    { stone: 2 },
    "rugged",
    "alpine-stone",
    "#979c9e",
  ),
  "alpine-pasture": b(
    "Alpine pasture",
    "wool",
    { wool: 1 },
    "rugged",
    "alpine-pasture",
    "#8e9a79",
  ),
  "bare-peaks": b("Bare Peaks", "peaks", {}, "rugged", "bare-peaks", "#929ca8"),
  "alluvial-clay": b(
    "Alluvial clay banks",
    "brick",
    { brick: 2 },
    "flat",
    "subtropical-clay",
    "#a8765a",
  ),
  "river-woods": b(
    "River woods",
    "lumber",
    { lumber: 1 },
    "forest",
    "river-woods",
    "#548e69",
  ),
  "wildlife-grassland": b(
    "Wildlife grassland",
    "hides",
    { hides: 2 },
    "flat",
    "wildlife-grassland",
    "#bca35d",
  ),
  "dry-woodland": b(
    "Dry woodland",
    "lumber",
    { lumber: 1 },
    "forest",
    "dry-woodland",
    "#8c9253",
  ),
};
/** Printed annual baseline, including the growing conditions of this region. */
export function biomeYield(
  biome: Biome,
  climate?: Climate,
): BiomeInfo["yield"] {
  const output = { ...BIOME_INFO[biome].yield };
  if (biome === "rice-field")
    output.grain =
      climate === "monsoon" ? 1 : climate === "subtropical" ? 2 : 3;
  if (biome === "barley-fields" && climate === "oceanic") output.grain = 2;
  if (
    biome === "turnip-fields" &&
    (climate === "temperate" || climate === "oceanic")
  )
    output.grain = 2;
  return output;
}
export interface ClimateInfo {
  name: string;
  color: string;
  land: number;
  terrain: [Biome, number][];
  water: [Biome, number][];
  compatible: Climate[];
}
export const CLIMATE_INFO: Record<Climate, ClimateInfo> = {
  temperate: {
    name: "Temperate",
    color: "#84a66b",
    land: 0.5,
    terrain: [
      ["golden-fields", 7],
      ["chernozem-wheat", 2],
      ["oat-fields", 4],
      ["turnip-fields", 4],
      ["pasture", 9],
      ["cattle-pasture", 8],
      ["woods", 17],
      ["gold", 5],
      ["clay", 12],
      ["stone", 10],
      ["iron", 10],
      ["coal", 10],
      ["salt-flats", 2],
    ],
    water: [
      ["fish", 0.15],
      ["whale", 0.05],
    ],
    compatible: [
      "steppe",
      "mediterranean",
      "cold",
      "tropical",
      "oceanic",
      "alpine",
      "subtropical",
      "prairie",
    ],
  },
  cold: {
    name: "Cold",
    color: "#719a99",
    land: 0.55,
    terrain: [
      ["forest", 30],
      ["hunting-forest", 6],
      ["reindeer-range", 4],
      ["barley-fields", 7],
      ["turnip-fields", 3],
      ["rough-pasture", 5],
      ["gold", 5],
      ["coal", 10],
      ["iron", 10],
      ["stone", 10],
      ["clay", 10],
    ],
    water: [
      ["fish", 0.2],
      ["cod", 0.1],
      ["whale", 0.1],
    ],
    compatible: [
      "temperate",
      "steppe",
      "arctic",
      "oceanic",
      "alpine",
      "prairie",
    ],
  },
  arctic: {
    name: "Arctic",
    color: "#c1e0ed",
    land: 0.4,
    terrain: [
      ["snow-plain", 35],
      ["reindeer-range", 5],
      ["seal-grounds", 15],
      ["arctic-iron", 20],
      ["arctic-stone", 15],
      ["arctic-gold", 10],
    ],
    water: [
      ["ice", 0.3],
      ["fish", 0.2],
      ["cod", 0.2],
      ["whale", 0.2],
    ],
    compatible: ["cold", "alpine", "glacial"],
  },
  steppe: {
    name: "Steppe",
    color: "#b9ad75",
    land: 0.65,
    terrain: [
      ["steppe-plain", 25],
      ["chernozem-wheat", 4],
      ["cattle-savanna", 16],
      ["millet-fields", 10],
      ["pasture", 10],
      ["woods", 7],
      ["stone", 10],
      ["iron", 5],
      ["coal", 5],
      ["clay", 5],
      ["gold", 3],
    ],
    water: [
      ["fish", 0.15],
      ["whale", 0.05],
    ],
    compatible: [
      "cold",
      "temperate",
      "mediterranean",
      "desert",
      "alpine",
      "savanna",
      "andean",
      "prairie",
    ],
  },
  mediterranean: {
    name: "Mediterranean",
    color: "#c9b37d",
    land: 0.4,
    terrain: [
      ["golden-fields", 3],
      ["barley-fields", 2],
      ["olive-grove", 20],
      ["escarpment", 20],
      ["woods", 5],
      ["rough-pasture", 10],
      ["goat-pasture", 5],
      ["salt-flats", 5],
      ["gold", 7],
      ["coal", 10],
      ["iron", 13],
    ],
    water: [
      ["fish", 0.15],
      ["whale", 0.05],
    ],
    compatible: ["temperate", "steppe", "desert", "oceanic", "subtropical"],
  },
  tropical: {
    name: "Tropical",
    color: "#4f9667",
    land: 0.5,
    terrain: [
      ["jungle", 25],
      ["tropical-woods", 10],
      ["rice-field", 25],
      ["clay", 15],
      ["gold", 5],
      ["stone", 5],
      ["coal", 5],
      ["iron", 5],
      ["salt-flats", 5],
    ],
    water: [
      ["fish", 0.1],
      ["whale", 0.05],
    ],
    compatible: [
      "temperate",
      "desert",
      "subtropical",
      "savanna",
      "monsoon",
      "mesoamerican",
    ],
  },
  desert: {
    name: "Desert",
    color: "#d6ab66",
    land: 0.5,
    terrain: [
      ["desert", 25],
      ["goat-pasture", 5],
      ["gold", 10],
      ["iron", 12],
      ["stone", 12],
      ["coal", 6],
      ["oasis", 10],
      ["salt-flats", 20],
    ],
    water: [
      ["fish", 0.08],
      ["whale", 0.03],
    ],
    compatible: [
      "tropical",
      "mediterranean",
      "steppe",
      "savanna",
      "hyperarid",
      "andean",
      "prairie",
    ],
  },
  oceanic: {
    name: "Oceanic",
    color: "#438caa",
    land: 0.35,
    terrain: [
      ["coastal-pasture", 17],
      ["cattle-pasture", 8],
      ["woods", 20],
      ["barley-fields", 8],
      ["turnip-fields", 2],
      ["golden-fields", 5],
      ["clay", 10],
      ["coastal-cliffs", 15],
      ["coal", 8],
      ["iron", 5],
      ["gold", 2],
    ],
    water: [
      ["fish", 0.2],
      ["cod", 0.1],
      ["whale", 0.1],
    ],
    compatible: ["temperate", "cold", "mediterranean"],
  },
  alpine: {
    name: "Alpine",
    color: "#8985ac",
    land: 0.75,
    terrain: [
      ["mountain-quarry", 20],
      ["iron", 15],
      ["coal", 10],
      ["alpine-pasture", 10],
      ["goat-pasture", 5],
      ["barley-fields", 7],
      ["turnip-fields", 3],
      ["forest", 10],
      ["gold", 5],
      ["clay", 5],
      ["bare-peaks", 10],
    ],
    water: [
      ["fish", 0.1],
      ["cod", 0.1],
      ["whale", 0.03],
    ],
    compatible: ["cold", "arctic", "temperate", "steppe", "glacial", "andean"],
  },
  subtropical: {
    name: "Subtropical",
    color: "#3cae85",
    land: 0.55,
    terrain: [
      ["alluvial-clay", 25],
      ["rice-field", 15],
      ["sorghum-fields", 5],
      ["river-woods", 15],
      ["cattle-pasture", 5],
      ["jungle", 10],
      ["stone", 10],
      ["coal", 5],
      ["iron", 5],
      ["salt-flats", 3],
      ["gold", 2],
    ],
    water: [
      ["fish", 0.15],
      ["whale", 0.03],
    ],
    compatible: [
      "tropical",
      "temperate",
      "mediterranean",
      "savanna",
      "monsoon",
      "andean",
      "mesoamerican",
    ],
  },
  savanna: {
    name: "Savanna",
    color: "#d18e4d",
    land: 0.7,
    terrain: [
      ["wildlife-grassland", 30],
      ["cattle-savanna", 5],
      ["millet-fields", 20],
      ["dry-woodland", 10],
      ["rough-pasture", 10],
      ["iron", 10],
      ["clay", 5],
      ["stone", 5],
      ["gold", 3],
      ["salt-flats", 2],
    ],
    water: [
      ["fish", 0.1],
      ["whale", 0.03],
    ],
    compatible: [
      "tropical",
      "desert",
      "steppe",
      "subtropical",
      "monsoon",
      "mesoamerican",
    ],
  },
  glacial: {
    name: "Glacial",
    color: "#a8cbdc",
    land: 0.45,
    terrain: [
      ["snow-plain", 55],
      ["bare-peaks", 15],
      ["seal-grounds", 8],
      ["arctic-iron", 10],
      ["arctic-stone", 8],
      ["arctic-gold", 4],
    ],
    water: [
      ["ice", 0.55],
      ["fish", 0.1],
      ["cod", 0.15],
      ["whale", 0.12],
    ],
    compatible: ["arctic", "alpine"],
  },
  hyperarid: {
    name: "Hyperarid",
    color: "#bd8050",
    land: 0.9,
    terrain: [
      ["desert", 55],
      ["bare-peaks", 5],
      ["salt-flats", 12],
      ["iron", 10],
      ["stone", 7],
      ["gold", 6],
      ["oasis", 3],
      ["coal", 2],
    ],
    water: [
      ["fish", 0.03],
      ["whale", 0.01],
    ],
    compatible: ["desert"],
  },
  monsoon: {
    name: "Monsoon",
    color: "#357d73",
    land: 0.3,
    terrain: [
      ["jungle", 20],
      ["tropical-woods", 15],
      ["river-woods", 10],
      ["rice-field", 15],
      ["alluvial-clay", 15],
      ["bare-peaks", 15],
      ["stone", 5],
      ["iron", 2],
      ["coal", 1],
      ["gold", 2],
    ],
    water: [
      ["fish", 0.1],
      ["whale", 0.02],
    ],
    compatible: ["tropical", "subtropical", "savanna"],
  },
  andean: {
    name: "Andean",
    color: "#998b77",
    land: 0.75,
    terrain: [
      ["potato-fields", 18],
      ["alpaca-pasture", 14],
      ["mountain-quarry", 16],
      ["iron", 10],
      ["gold", 6],
      ["salt-flats", 6],
      ["clay", 5],
      ["river-woods", 5],
      ["bare-peaks", 15],
      ["snow-plain", 5],
    ],
    water: [["fish", 0.12]],
    compatible: ["alpine", "steppe", "desert", "subtropical", "mesoamerican"],
  },
  prairie: {
    name: "Prairie",
    color: "#b5a35f",
    land: 0.7,
    terrain: [
      ["steppe-plain", 32],
      ["maize-field", 12],
      ["sunflower-fields", 6],
      ["bison-range", 16],
      ["river-woods", 8],
      ["clay", 8],
      ["stone", 6],
      ["coal", 5],
      ["iron", 4],
      ["gold", 1],
      ["salt-flats", 2],
    ],
    water: [["fish", 0.1]],
    compatible: ["cold", "temperate", "steppe", "desert", "mesoamerican"],
  },
  mesoamerican: {
    name: "Mesoamerican",
    color: "#568c65",
    land: 0.45,
    terrain: [
      ["maize-field", 20],
      ["chinampa-gardens", 6],
      ["turkey-grounds", 8],
      ["cloud-forest", 16],
      ["tropical-woods", 10],
      ["clay", 12],
      ["volcanic-quarry", 10],
      ["iron", 8],
      ["gold", 4],
      ["salt-flats", 4],
      ["coal", 2],
    ],
    water: [
      ["fish", 0.15],
      ["whale", 0.05],
    ],
    compatible: ["tropical", "subtropical", "savanna", "andean", "prairie"],
  },
};

export const AMERICAN_CLIMATES: readonly Climate[] = [
  "andean",
  "prairie",
  "mesoamerican",
];

const NEW_CLIMATES: Climate[] = ["oceanic", "alpine", "subtropical", "savanna"];
export const EXTREME_CLIMATES: readonly Climate[] = [
  "glacial",
  "hyperarid",
  "monsoon",
];
/** Extremes remain possible starting regions, with lower relative frequency. */
export function climateInitialWeight(climate: Climate): number {
  return EXTREME_CLIMATES.includes(climate) ? 0.35 : 1;
}
const TRANSITION_WEIGHTS: Partial<
  Record<Climate, Partial<Record<Climate, number>>>
> = {
  temperate: { cold: 1.5 },
  steppe: { cold: 1.5 },
  mediterranean: { desert: 0.5, steppe: 0.5 },
  tropical: { desert: 2 },
  desert: { tropical: 2 },
  cold: { arctic: 2 },
  oceanic: { temperate: 2 },
  alpine: { cold: 2, arctic: 2 },
  subtropical: { tropical: 2 },
  savanna: { tropical: 2 },
  glacial: { arctic: 2, alpine: 1 },
  hyperarid: { desert: 2 },
  monsoon: { tropical: 2, subtropical: 1, savanna: 1 },
  andean: { alpine: 2 },
  prairie: { steppe: 2 },
  mesoamerican: { subtropical: 2 },
};
/** Relative destination weights, after checking immediate-neighbor compatibility. */
export function climateTransitionWeight(from: Climate, to: Climate): number {
  if (from === to) return 1;
  if (AMERICAN_CLIMATES.includes(to))
    return AMERICAN_CLIMATES.includes(from) ? 1 : 0.75;
  if (AMERICAN_CLIMATES.includes(from))
    return TRANSITION_WEIGHTS[from]?.[to] ?? 1;
  return (
    TRANSITION_WEIGHTS[from]?.[to] ??
    (EXTREME_CLIMATES.includes(to)
      ? 0.5
      : !NEW_CLIMATES.includes(from) && NEW_CLIMATES.includes(to)
        ? 0.5
        : 1)
  );
}
export function compatibleClimate(a: Climate, b: Climate) {
  return (
    a === b ||
    (CLIMATE_INFO[a].compatible.includes(b) &&
      CLIMATE_INFO[b].compatible.includes(a))
  );
}
export function waterProbabilities(
  climate: Climate,
  openWater = false,
): [Biome, number][] {
  let remaining = 1;
  const result: [Biome, number][] = CLIMATE_INFO[climate].water.map(
    ([biome, chance]) => {
      chance = Math.min(1, chance * (openWater && biome === "whale" ? 2 : 1));
      const value = remaining * chance;
      remaining *= 1 - chance;
      return [biome, value];
    },
  );
  return [...result, ["water", remaining]];
}
