import type { SpecialistBranch } from "./infrastructure-specialists";
/** Local seasonal livelihoods and bounded construction substitutions. */
export const LIVELIHOOD_BRANCHES = [
  {
    id: "rice-fish-refuges",
    track: "soil",
    site: "rice",
    goods: ["fish"],
    name: "Rice–fish refuges",
    fr: "Refuges riz-poissons",
    description:
      "Refuge trenches shelter fish between the rice rows; screened sluices retain the stock through the wet growing season.",
    descriptionFr:
      "Des fossés abritent les poissons entre les rangs de riz ; des vannes grillagées retiennent les élevages pendant la saison humide.",
    stages: [
      "Refuge trench",
      "Screened paddy sluices",
      "Connected nursery ponds",
      "Managed rice–fish holdings",
    ],
    stagesFr: [
      "Fossé refuge",
      "Vannes de rizière grillagées",
      "Bassins de nurserie reliés",
      "Exploitations riz-poissons organisées",
    ],
    primary: false,
    effect: "yield",
    biomes: ["rice-field", "flood-rice"],
    climates: ["tropical", "subtropical", "monsoon", "mesoamerican"],
    freshwater: true,
  },
  {
    id: "spring-sap-groves",
    track: "forestry",
    site: "forest",
    goods: ["grain"],
    name: "Spring sap groves",
    fr: "Bosquets à sève printanière",
    description:
      "Selected maple and birch stands supply sweet sap during the spring thaw. Covered vessels and evaporation pans preserve the short harvest.",
    descriptionFr:
      "Des érables et bouleaux sélectionnés fournissent une sève sucrée au dégel. Récipients couverts et bassines préservent cette courte récolte.",
    stages: [
      "Sap spiles and buckets",
      "Covered gathering runs",
      "Evaporation house",
      "Coordinated sap works",
    ],
    stagesFr: [
      "Chalumeaux et seaux",
      "Tournées de collecte abritées",
      "Cabane d’évaporation",
      "Ateliers de sève coordonnés",
    ],
    primary: false,
    effect: "yield",
    biomes: ["woods", "river-woods", "old-growth-forest"],
    climates: ["temperate", "cold", "oceanic"],
  },
  {
    id: "kelp-longlines",
    track: "fishery",
    site: "any",
    goods: ["fish"],
    name: "Edible seaweed lines",
    fr: "Cordages à algues comestibles",
    description:
      "Anchored cultivation ropes carry edible seaweeds in cool coastal water, providing a harvest independent of passing fish shoals.",
    descriptionFr:
      "Des cordages ancrés portent des algues comestibles dans les eaux côtières fraîches, indépendamment des bancs de poissons de passage.",
    stages: [
      "Seeded shore ropes",
      "Anchored growing lines",
      "Seaweed nursery rafts",
      "Coordinated coastal gardens",
    ],
    stagesFr: [
      "Cordages ensemencés",
      "Lignes de culture ancrées",
      "Radeaux de nurserie",
      "Jardins côtiers coordonnés",
    ],
    primary: false,
    effect: "yield",
    coastal: true,
    waterways: ["coast", "shoal"],
    climates: ["cold", "temperate", "oceanic", "temperate-rainforest"],
  },
  {
    id: "reed-thatch-beds",
    track: "fishery",
    site: "any",
    goods: ["lumber"],
    name: "Winter reed beds",
    fr: "Roselières de coupe hivernale",
    description:
      "Managed freshwater reed margins supply dry thatch and light building material after the stems have matured.",
    descriptionFr:
      "Des roselières d’eau douce entretenues fournissent chaume sec et matériaux légers après la maturité des tiges.",
    stages: [
      "Marked cutting beds",
      "Rotating reed plots",
      "Covered bundle yard",
      "Coordinated thatching depot",
    ],
    stagesFr: [
      "Parcelles de coupe balisées",
      "Roselières en rotation",
      "Chantier de bottes couvert",
      "Dépôt de chaume coordonné",
    ],
    primary: false,
    effect: "yield",
    waterways: ["river", "lake"],
    climates: ["temperate", "oceanic", "mediterranean"],
  },
  {
    id: "coconut-coir-yards",
    track: "forestry",
    site: "forest",
    goods: ["lumber"],
    name: "Coconut fibre yards",
    fr: "Chantiers de fibre de coco",
    description:
      "Coconut husks are retted, beaten and twisted into cordage and padding for construction around the grove.",
    descriptionFr:
      "Les enveloppes de noix de coco sont rouies, battues et torsadées en cordages et garnitures pour les ouvrages de la palmeraie.",
    stages: [
      "Husk retting pits",
      "Fibre beating yard",
      "Coir spinning shed",
      "Integrated fibre workshop",
    ],
    stagesFr: [
      "Fosses de rouissage",
      "Chantier de battage",
      "Atelier de filage du coir",
      "Atelier de fibres intégré",
    ],
    primary: false,
    effect: "yield",
    biomes: ["island-palms"],
    climates: ["tropical-maritime"],
  },
  {
    id: "mine-stone-stowing",
    track: "mining",
    site: "any",
    goods: ["ore", "coal", "gold"],
    name: "Mine stone stowing",
    fr: "Remblayage en pierre de mine",
    description:
      "Sorted waste rock fills local foundations and drainage beds, sparing dressed masonry in later mine works.",
    descriptionFr:
      "Les stériles triés remplissent fondations et drains locaux, économisant la maçonnerie taillée des futurs ouvrages miniers.",
    stages: [
      "Sorted waste-rock bays",
      "Graded stowing yard",
      "Mechanical stone screens",
      "Coordinated backfill works",
    ],
    stagesFr: [
      "Cases de stériles triés",
      "Chantier de remblai calibré",
      "Cribles mécaniques",
      "Ouvrages de remblai coordonnés",
    ],
    primary: false,
    effect: "yield",
  },
  {
    id: "date-pit-feeders",
    track: "soil",
    site: "orchard",
    goods: ["meat"],
    name: "Date-pit feed mills",
    fr: "Moulins à noyaux de dattes",
    description:
      "Ground date stones and stored fruit trimmings supplement livestock feed after the main date harvest.",
    descriptionFr:
      "Les noyaux moulus et résidus de fruits conservés complètent la ration du bétail après la grande récolte des dattes.",
    stages: [
      "Pit drying mats",
      "Date-stone crushing yard",
      "Feed grinding mill",
      "Oasis feed depot",
    ],
    stagesFr: [
      "Nattes de séchage des noyaux",
      "Chantier de concassage",
      "Moulin fourrager",
      "Dépôt fourrager d’oasis",
    ],
    primary: false,
    effect: "yield",
    biomes: ["oasis"],
    climates: ["desert", "hyperarid", "semiarid"],
  },
  {
    id: "upland-leaf-hay",
    track: "forestry",
    site: "forest",
    goods: ["lumber"],
    name: "Upland leaf-hay lofts",
    fr: "Fenils de feuilles montagnards",
    description:
      "Bundles of leafy broadleaved branches are dried under cover to supplement small livestock during the lean woodland season.",
    descriptionFr:
      "Des branches feuillues séchées à couvert complètent le fourrage du petit bétail pendant la saison forestière pauvre.",
    stages: [
      "Leaf-fodder racks",
      "Ventilated branch loft",
      "Leaf-hay handling yard",
      "Upland fodder depot",
    ],
    stagesFr: [
      "Claies à feuillage",
      "Grenier à branches ventilé",
      "Chantier de foin de feuilles",
      "Dépôt fourrager montagnard",
    ],
    primary: false,
    effect: "yield",
    biomes: ["woods", "river-woods"],
    climates: ["temperate", "oceanic", "alpine"],
    minElevation: 0.65,
  },
  {
    id: "salt-graduation-walls",
    track: "saltworks",
    site: "any",
    goods: ["salt"],
    name: "Brine graduation walls",
    fr: "Murs de graduation de saumure",
    description:
      "Brine trickles through brushwood walls before reaching the pans, increasing concentration during damp working seasons.",
    descriptionFr:
      "La saumure ruisselle sur des murs de branchages avant les bassins, améliorant sa concentration pendant les saisons humides.",
    stages: [
      "Brushwood drip racks",
      "Raised brine channels",
      "Pumped graduation wall",
      "Linked concentration yard",
    ],
    stagesFr: [
      "Claies de ruissellement",
      "Canaux à saumure surélevés",
      "Mur de graduation pompé",
      "Chantier de concentration relié",
    ],
    effect: "wet",
    climates: ["temperate", "oceanic", "cold"],
  },
  {
    id: "fog-orchard-screens",
    track: "soil",
    site: "orchard",
    goods: ["grain"],
    name: "Fog-catching orchard screens",
    fr: "Filets à brume des vergers",
    description:
      "Mesh panels on exposed dry coasts intercept passing fog and direct the droplets into covered root-zone cisterns.",
    descriptionFr:
      "Des filets sur les côtes sèches exposées captent la brume et dirigent les gouttelettes vers des citernes racinaires couvertes.",
    stages: [
      "Fog mesh panels",
      "Covered collection gutters",
      "Wind-braced mesh field",
      "Coastal fog-water works",
    ],
    stagesFr: [
      "Panneaux à brume",
      "Gouttières couvertes",
      "Filets renforcés au vent",
      "Ouvrages côtiers de collecte",
    ],
    effect: "dry",
    biomes: ["oasis"],
    climates: ["desert", "semiarid"],
    coastal: true,
  },
  {
    id: "recession-fish-pools",
    track: "soil",
    site: "cereal",
    goods: ["fish"],
    name: "Recession fish pools",
    fr: "Bassins piscicoles de décrue",
    description:
      "Retained floodwater in screened side pools supports a small fish harvest after the cereal fields have been reaped.",
    descriptionFr:
      "L’eau de crue retenue dans des bassins latéraux grillagés permet une petite récolte de poissons après la moisson.",
    stages: [
      "Screened side pool",
      "Retained-water ponds",
      "Linked refuge basins",
      "Managed recession fishery",
    ],
    stagesFr: [
      "Bassin latéral grillagé",
      "Étangs de retenue",
      "Bassins refuges reliés",
      "Pêcherie de décrue organisée",
    ],
    primary: false,
    effect: "yield",
    biomes: ["flood-wheat", "flood-sorghum"],
    climates: ["desert", "semiarid", "savanna", "monsoon", "subtropical"],
    freshwater: true,
  },
  {
    id: "qiviut-gathering",
    track: "hunting",
    site: "open",
    goods: ["wool"],
    name: "Musk-ox underwool gathering",
    fr: "Collecte du duvet de bœuf musqué",
    description:
      "Quiet gathering routes collect soft underwool shed on bushes and resting grounds during the spring moult.",
    descriptionFr:
      "Des parcours discrets permettent de ramasser le duvet laissé sur les buissons et reposoirs pendant la mue printanière.",
    stages: [
      "Marked moult grounds",
      "Underwool gathering rounds",
      "Covered fibre sorting hut",
      "Polar underwool depot",
    ],
    stagesFr: [
      "Sites de mue balisés",
      "Tournées de collecte",
      "Cabane de tri couverte",
      "Dépôt de duvet polaire",
    ],
    primary: false,
    effect: "yield",
    climates: ["arctic", "glacial", "tundra"],
    biomes: ["snow-plain", "musk-ox-range", "tundra-heath"],
  },
] as const satisfies readonly SpecialistBranch[];
