import type { SpecialistBranch } from "./infrastructure-specialists";

// Small complementary works: stable site restrictions, independently purchased
// stages, and the same conservative annual budget as the original specialists.
const niche = (
  id: string,
  track: SpecialistBranch["track"],
  site: SpecialistBranch["site"],
  goods: SpecialistBranch["goods"],
  name: string,
  fr: string,
  description: string,
  descriptionFr: string,
  stages: string,
  stagesFr: string,
  settings: Partial<SpecialistBranch> = {},
): SpecialistBranch => ({
  id,
  track,
  site,
  goods,
  name,
  fr,
  description,
  descriptionFr,
  effect: "yield",
  stages: stages.split("|"),
  stagesFr: stagesFr.split("|"),
  ...settings,
});
const dry = [
  "desert",
  "hyperarid",
  "semiarid",
  "savanna",
  "steppe",
  "mediterranean",
] as const;
const humid = [
  "oceanic",
  "temperate-rainforest",
  "tropical",
  "monsoon",
  "equatorial-wetlands",
  "tropical-maritime",
] as const;
export const NICHE_BRANCHES: readonly SpecialistBranch[] = [
  niche(
    "date-pollination",
    "soil",
    "orchard",
    ["grain"],
    "Oasis pollination",
    "Pollinisation des oasis",
    "Carefully stored pollen and climbing platforms improve fruit set in the date palms.",
    "Le pollen conservé au sec et les plateformes de grimpe améliorent la fructification des dattiers.",
    "Pollen baskets|Palm climbing platforms|Pollen drying house|Mechanical pollination platform",
    "Paniers à pollen|Plateformes de grimpe|Séchoir à pollen|Plateforme de pollinisation mécanique",
    { biomes: ["oasis"], climates: dry, finishing: { cloth: 1 } },
  ),
  niche(
    "date-bunch-covers",
    "soil",
    "orchard",
    ["grain"],
    "Date bunch shelters",
    "Protection des régimes de dattes",
    "Breathable covers shelter ripening dates from untimely rain while leaving air around the fruit.",
    "Des housses aérées abritent les dattes mûrissantes des pluies tardives sans retenir l’humidité.",
    "Woven bunch hoods|Covered bunch frames|Canvas bunch workshop|Ventilated fruit shelters",
    "Capuchons tressés|Armatures pour régimes|Atelier de housses|Abris fruitiers ventilés",
    {
      biomes: ["oasis"],
      climates: dry,
      finishing: { cloth: 2 },
    },
  ),
  niche(
    "sago-washing",
    "soil",
    "orchard",
    ["grain"],
    "Sago starch washing",
    "Lavage de la fécule de sagou",
    "Freshwater troughs separate starch from palm pith; successive settling basins recover finer meal.",
    "Des auges d’eau douce séparent la fécule de la moelle des palmiers ; les bassins de décantation récupèrent la farine fine.",
    "Pith washing trough|Starch settling basins|Mechanical pith rasp|Starch washing works",
    "Auge de lavage|Bassins à fécule|Râpe mécanique à moelle|Lavoir à fécule",
    { biomes: ["sago-grove"], freshwater: true, finishing: { ceramics: 2 } },
  ),
  niche(
    "breadfruit-fermentation",
    "soil",
    "orchard",
    ["grain"],
    "Breadfruit fermentation",
    "Fermentation du fruit à pain",
    "Leaf-lined pits preserve sound breadfruit pulp, recovering more food from the grove’s harvest.",
    "Des fosses tapissées de feuilles conservent la pulpe saine et valorisent davantage la récolte des arbres à pain.",
    "Leaf-lined pits|Stone-lined fermentation pits|Covered pulp house|Fermentation chambers",
    "Fosses tapissées de feuilles|Fosses maçonnées|Halle à pulpe|Chambres de fermentation",
    {
      biomes: ["breadfruit-grove"],
      maxElevation: 0.65,
      finishing: { stone: 2 },
    },
  ),
  niche(
    "olive-catching-nets",
    "soil",
    "oilseed",
    ["grain"],
    "Olive catching nets",
    "Filets de récolte des olives",
    "Nets beneath the trees collect sound olives before they are bruised or lost among stones.",
    "Des filets sous les arbres recueillent les olives saines avant qu’elles ne s’abîment parmi les pierres.",
    "Woven catching sheets|Terrace net anchors|Mechanical net reels|Orchard collection gantries",
    "Toiles de récolte|Ancrages de terrasse|Enrouleurs mécaniques|Portiques de collecte",
    { biomes: ["olive-grove"], finishing: { cloth: 2 } },
  ),
  niche(
    "sunflower-dehulling",
    "soil",
    "oilseed",
    ["oil"],
    "Sunflower seed preparation",
    "Préparation des graines de tournesol",
    "Cleanly hulled seeds give the presses a richer charge with fewer woody husks.",
    "Des graines bien décortiquées apportent aux presses une matière plus riche, débarrassée des enveloppes ligneuses.",
    "Seed rubbing boards|Hulling rollers|Mechanical dehuller|Seed preparation mill",
    "Planches de décorticage|Rouleaux décortiqueurs|Décortiqueuse mécanique|Moulin de préparation",
    { biomes: ["sunflower-fields"] },
  ),
  niche(
    "chinampa-silt-nurseries",
    "soil",
    "gardens",
    ["grain"],
    "Canal-mud seedbeds",
    "Pépinières de limon des canaux",
    "Moist blocks of canal mud shelter young plants before they are moved to the garden beds.",
    "Des mottes de limon humide abritent les jeunes plants avant leur transfert vers les planches cultivées.",
    "Mud-block nursery|Sheltered transplant beds|Nursery lifting frames|Garden propagation house",
    "Pépinière sur mottes|Planches de repiquage abritées|Châssis de levage|Maison de multiplication",
    { biomes: ["chinampa-gardens"], freshwater: true, fertile: true },
  ),
  niche(
    "potato-sprouting",
    "soil",
    "roots",
    ["grain"],
    "Potato seed stores",
    "Réserves de plants de pommes de terre",
    "Cool, softly lit stores keep seed tubers sound and encourage sturdy sprouts before planting.",
    "Des réserves fraîches et légèrement éclairées préservent les tubercules et favorisent des germes vigoureux avant plantation.",
    "Sprouting trays|Ventilated seed loft|Seed-tuber grader|Controlled sprouting house",
    "Clayettes de germination|Grenier à plants ventilé|Trieur de tubercules|Germoir régulé",
    {
      biomes: ["potato-fields"],
      climates: ["andean", "prairie", "mesoamerican"],
    },
  ),
  niche(
    "paddy-level-surveys",
    "irrigation",
    "rice",
    ["grain"],
    "Paddy water levelling",
    "Nivellement hydraulique des rizières",
    "Level marks and carefully graded beds spread scarce irrigation water evenly between rice plants.",
    "Des repères de niveau et des planches ajustées répartissent uniformément l’eau d’irrigation entre les plants de riz.",
    "Water-level stakes|Surveyed field beds|Precision levelling gear|Coordinated paddy levelling",
    "Piquets de niveau|Planches arpentées|Matériel de nivellement précis|Nivellement coordonné des rizières",
    { effect: "dry" },
  ),
  niche(
    "dryland-dust-mulch",
    "catchments",
    "dry-crop",
    ["grain"],
    "Dryland surface cultivation",
    "Travail superficiel des terres sèches",
    "Shallow cultivation breaks surface crusts after rain and limits moisture loss before the crop closes its canopy.",
    "Un travail peu profond rompt les croûtes après la pluie et freine les pertes d’eau avant la fermeture du couvert végétal.",
    "Light surface hoes|Shallow tine harrows|Depth-controlled cultivator|Precision surface cultivation",
    "Houes légères|Herses superficielles|Cultivateur à profondeur réglée|Travail superficiel de précision",
    { effect: "dry", climates: dry, maxElevation: 0.65 },
  ),
  niche(
    "mountain-haylofts",
    "husbandry",
    "upland",
    ["meat", "wool"],
    "Mountain haylofts",
    "Fenils montagnards",
    "Raised, airy haylofts keep mountain fodder dry through wet spells and preserve winter feed for the herds.",
    "Des fenils surélevés et aérés gardent le fourrage montagnard au sec et préservent les réserves hivernales.",
    "Raised hay racks|Ventilated mountain loft|Hay lifting gear|Fan-ventilated hay barn",
    "Claies à foin surélevées|Fenil montagnard ventilé|Monte-foin|Grange à ventilation forcée",
    { effect: "cold", climates: ["alpine", "andean", "cold", "oceanic"] },
  ),
  niche(
    "browse-fodder",
    "husbandry",
    "warm",
    ["meat", "hides"],
    "Dry-season browse reserves",
    "Réserves de fourrage ligneux",
    "Cut branches and carefully stored leaves supplement dry-season grazing for browsing livestock.",
    "Les branches coupées et les feuilles conservées complètent le pâturage sec des troupeaux qui broutent les ligneux.",
    "Leaf fodder racks|Browse storage yard|Branch chaff cutter|Covered browse depot",
    "Claies à feuilles fourragères|Cour de stockage du feuillage|Hache-branches|Dépôt de feuillage couvert",
    {
      biomes: ["goat-pasture", "cattle-savanna"],
      climates: dry,
      effect: "dry",
    },
  ),
  niche(
    "wool-washing",
    "husbandry",
    "wool",
    ["wool"],
    "Fleece washing yards",
    "Lavoirs à laine",
    "Freshwater washing troughs and draining screens recover clean fleece with less handling waste.",
    "Les auges d’eau douce et les claies d’égouttage récupèrent les toisons propres avec moins de pertes.",
    "Fleece washing trough|Draining wool screens|Mechanical fleece washer|Wool washing house",
    "Auge à toisons|Claies d’égouttage|Laveuse mécanique|Lavoir à laine",
    { freshwater: true, finishing: { ceramics: 2 } },
  ),
  niche(
    "flood-meadow-hay",
    "husbandry",
    "any",
    ["meat", "wool"],
    "Flood-meadow hay recovery",
    "Fenaison des prés inondables",
    "Raised drying frames help bring in meadow hay between wet periods without leaving it on soaked ground.",
    "Des séchoirs surélevés permettent de rentrer le foin entre les périodes humides sans le laisser sur le sol détrempé.",
    "Meadow hay trestles|Raised mowing depot|Hay turning machinery|Meadow drying barn",
    "Tréteaux de prairie|Dépôt de fenaison surélevé|Faneuse mécanique|Séchoir de prairie",
    { biomes: ["flood-meadow"], seasonalWeights: [1, 3, 2, 0.5] },
  ),
  niche(
    "river-log-booms",
    "forestry",
    "forest",
    ["lumber"],
    "River timber collection",
    "Collecte du bois flotté",
    "Booms and sorting landings gather timber along the riverbank before logs are lost downstream.",
    "Des estacades et des débarcadères de tri rassemblent le bois avant que les grumes ne soient emportées en aval.",
    "Timber catch boom|Sorting boom pens|Mechanical log winch|Timber sorting basin",
    "Estacade à grumes|Enclos de tri flottants|Treuil à grumes|Bassin de tri du bois",
    { biomes: ["river-woods"], freshwater: true, finishing: { leather: 1 } },
  ),
  niche(
    "humid-timber-stickers",
    "forestry",
    "forest",
    ["lumber"],
    "Humid-forest seasoning",
    "Séchage des bois humides",
    "Spaced stacks and cross-ventilated sheds help freshly cut timber dry evenly despite damp weather.",
    "Des piles espacées et des hangars traversants permettent au bois frais de sécher régulièrement malgré l’humidité.",
    "Spacing battens|Cross-ventilated stacks|Adjustable drying shutters|Ventilated seasoning hall",
    "Tasseaux d’espacement|Piles ventilées|Volets de séchage réglables|Halle de séchage ventilée",
    { climates: humid, effect: "wet" },
  ),
  niche(
    "slope-log-chutes",
    "forestry",
    "upland",
    ["lumber"],
    "Mountain log chutes",
    "Glissoires à bois montagnardes",
    "Lined chutes guide felled timber down wooded slopes, reducing breakage on the way to the landing.",
    "Des glissoires revêtues guident les grumes sur les pentes boisées et réduisent la casse jusqu’au dépôt.",
    "Timber slide|Lined log chute|Controlled chute gates|Integrated chute landings",
    "Glissière à bois|Glissoire revêtue|Portes de régulation|Dépôts reliés aux glissoires",
    {
      minElevation: 0.65,
      seasonalWeights: [2, 2, 1, 0.5],
      finishing: { stone: 2 },
    },
  ),
  niche(
    "ore-jigging",
    "mining",
    "ore",
    ["ore"],
    "Water-jig ore separation",
    "Séparation du minerai par lavage",
    "Pulsing water sorts crushed ore by density, retaining useful heavy fragments from mixed material.",
    "L’eau pulsée trie le minerai concassé par densité et retient les fragments lourds utiles.",
    "Washing basket jig|Timber jig boxes|Mechanical ore jig|Graded separation house",
    "Panier de lavage|Bacs de séparation|Jig mécanique|Atelier de séparation graduée",
    { freshwater: true, finishing: { ceramics: 1 } },
  ),
  niche(
    "coal-washing",
    "mining",
    "coal",
    ["coal"],
    "Coal washery",
    "Lavoir à charbon",
    "Washing channels separate saleable coal from heavier stone and clay before loading.",
    "Des canaux de lavage séparent le charbon utilisable des pierres et de l’argile avant chargement.",
    "Coal washing channel|Settling wash yard|Mechanical coal jig|Coal preparation works",
    "Canal de lavage du charbon|Cour de décantation|Jig à charbon|Atelier de préparation du charbon",
    { freshwater: true, finishing: { stone: 2 } },
  ),
  niche(
    "gold-riffle-boxes",
    "mining",
    "gold",
    ["gold"],
    "Riffled gold sluices",
    "Sluices à traverses",
    "Riffles and collection mats catch dense gold particles while lighter washed material passes downstream.",
    "Des traverses et des tapis retiennent les particules d’or denses pendant que les matériaux légers sont entraînés par l’eau.",
    "Riffled sluice box|Mat-lined sluice run|Adjustable recovery tables|Fine-gold separation works",
    "Sluice à traverses|Rampe garnie de tapis|Tables de récupération réglables|Atelier de séparation de l’or fin",
    { freshwater: true, maxElevation: 0.65, finishing: { cloth: 2 } },
  ),
  niche(
    "cold-mine-portals",
    "mining",
    "cold",
    ["ore", "coal", "gold"],
    "Sheltered mine portals",
    "Entrées de mine abritées",
    "Recessed entrances and insulated doors keep drifting snow and biting winds away from the workings.",
    "Des entrées en retrait et des portes isolées tiennent la neige soufflée et les vents glacés à distance des galeries.",
    "Portal wind screens|Double mine doors|Insulated entrance gallery|Frost-sheltered portal vestibule",
    "Écrans coupe-vent|Doubles portes de mine|Galerie d’entrée isolée|Sas d’entrée protégé du gel",
    { effect: "cold", finishing: { stone: 2 } },
  ),
  niche(
    "clay-levigation",
    "quarrying",
    "clay",
    ["brick"],
    "Clay settling beds",
    "Bassins de décantation de l’argile",
    "Successive freshwater settling beds remove coarse grit and recover workable clay from mixed deposits.",
    "Des bassins successifs éliminent les gros grains et récupèrent l’argile utilisable des dépôts mêlés.",
    "Clay washing pit|Paired settling beds|Clay slurry agitator|Clay preparation house",
    "Fosse de lavage|Bassins jumelés|Agitateur de barbotine|Atelier de préparation de l’argile",
    { freshwater: true, finishing: { stone: 2 } },
  ),
  niche(
    "quarry-wedge-sets",
    "quarrying",
    "stone",
    ["stone"],
    "Controlled stone splitting",
    "Fendage contrôlé de la pierre",
    "Regular wedge holes split suitable rock along planned faces and leave fewer shattered blocks.",
    "Des trous de coins réguliers détachent la roche selon les faces prévues et limitent les blocs brisés.",
    "Matched wedge sets|Guided splitting benches|Pneumatic wedge drills|Precision splitting yard",
    "Jeux de coins assortis|Bancs de fendage guidé|Foreuses pneumatiques|Cour de fendage de précision",
    {
      biomes: ["stone", "arctic-stone", "mountain-quarry", "volcanic-quarry"],
      finishing: { ore: 2 },
    },
  ),
  niche(
    "peat-stack-ventilation",
    "quarrying",
    "peat",
    ["coal"],
    "Peat stack ventilation",
    "Ventilation des meules de tourbe",
    "Open-centred stacks and covered drying alleys expose more cut peat to moving air during the workable season.",
    "Des meules ajourées et des allées couvertes exposent davantage la tourbe coupée à l’air pendant la saison de travail.",
    "Open-centred peat stacks|Covered drying alleys|Peat turning frames|Ventilated peat store",
    "Meules de tourbe ajourées|Allées de séchage couvertes|Châssis de retournement|Réserve de tourbe ventilée",
    { seasonalWeights: [1, 4, 2, 0.5] },
  ),
  niche(
    "coastal-brine-feeders",
    "saltworks",
    "any",
    ["salt"],
    "Coastal brine forepans",
    "Avant-bassins de saumure côtière",
    "Seaward forepans settle suspended mud and concentrate incoming brine before it reaches the crystallising beds.",
    "Des avant-bassins côtiers décantent la vase et concentrent la saumure avant son arrivée aux cristallisoirs.",
    "Brine forepan|Linked forepan banks|Adjustable brine feeders|Coordinated salt-pan supply",
    "Avant-bassin de saumure|Digues d’avant-bassins|Alimentation réglable|Distribution coordonnée de saumure",
    {
      coastal: true,
      climates: dry,
      seasonalWeights: [1, 4, 2, 0.5],
      finishing: { brick: 2 },
    },
  ),
  niche(
    "salt-crystal-draining",
    "saltworks",
    "any",
    ["salt"],
    "Salt crystal draining",
    "Égouttage des cristaux de sel",
    "Perforated baskets and raised draining floors separate harvested crystals from excess bitter brine.",
    "Des paniers ajourés et des sols surélevés séparent les cristaux récoltés de l’excès de saumure amère.",
    "Draining salt baskets|Raised salt floors|Crystal draining screens|Salt draining hall",
    "Paniers à sel ajourés|Sols à sel surélevés|Cribles d’égouttage|Halle d’égouttage du sel",
    { biomes: ["salt-flats"], finishing: { ceramics: 2 } },
  ),
  niche(
    "fish-smokehouses",
    "fishery",
    "any",
    ["fish"],
    "Coastal fish smoking",
    "Fumage côtier du poisson",
    "Salted catches pass through ventilated smoke racks, preserving a larger share of landed fish in damp coastal air.",
    "Les prises salées passent sur des claies de fumage ventilées, préservant davantage de poisson dans l’air humide du littoral.",
    "Sheltered smoke rack|Masonry fish kiln|Controlled-draught smokehouse|Ventilated smoking hall",
    "Claie de fumage abritée|Four à poisson maçonné|Fumoir à tirage réglé|Halle de fumage ventilée",
    {
      coastal: true,
      climates: ["cold", "oceanic", "temperate-rainforest", "temperate"],
      finishing: { salt: 2, lumber: 2 },
    },
  ),
  niche(
    "tropical-fish-drying",
    "fishery",
    "any",
    ["fish"],
    "Raised tropical fish drying",
    "Séchage tropical sur claies",
    "Raised mesh racks keep catches clear of wet sand and let dry-season breezes pass beneath the fish.",
    "Des claies surélevées éloignent les prises du sable humide et laissent passer les brises sèches sous les poissons.",
    "Raised mesh racks|Screened drying yard|Adjustable drying frames|Covered catch-drying hall",
    "Claies grillagées|Cour de séchage protégée|Châssis réglables|Halle de séchage des prises",
    {
      coastal: true,
      climates: [
        "tropical",
        "monsoon",
        "tropical-maritime",
        "savanna",
        "semiarid",
      ],
      finishing: { cloth: 2, salt: 1 },
    },
  ),
  niche(
    "snow-game-sledges",
    "hunting",
    "open",
    ["meat"],
    "Snow-country game hauling",
    "Transport du gibier sur neige",
    "Low sledges and sheltered field depots bring more of a winter kill back from the open snow country.",
    "Des traîneaux bas et des dépôts abrités ramènent davantage des prises hivernales depuis les étendues enneigées.",
    "Game dragging sledge|Covered sledge depot|Improved hauling runners|Winter game transport yard",
    "Traîneau à gibier|Dépôt à traîneaux couvert|Patins de transport renforcés|Cour de transport hivernal",
    {
      climates: ["arctic", "tundra", "cold", "glacial"],
      seasonalWeights: [1, 0.5, 2, 4],
      finishing: { leather: 2 },
    },
  ),
  niche(
    "woodland-game-smoking",
    "hunting",
    "forest",
    ["meat"],
    "Woodland game smokehouses",
    "Fumoirs à gibier forestiers",
    "Sheltered smoking hearths beside the hunting paths preserve more meat from visiting woodland game.",
    "Des foyers de fumage abrités près des sentiers préservent davantage de viande du gibier de passage.",
    "Game smoking hearth|Covered game smokehouse|Adjustable smoke flues|Forest curing hall",
    "Foyer de fumage du gibier|Fumoir à gibier couvert|Conduits réglables|Halle forestière de salaison",
    { finishing: { salt: 2, lumber: 2 } },
  ),
  niche(
    "heath-berry-drying",
    "foraging",
    "any",
    ["grain"],
    "Heath berry drying",
    "Séchage des baies de lande",
    "Thin drying layers and sheltered airways recover more edible berries from the short heath harvest.",
    "De fines couches de séchage et des passages d’air abrités valorisent davantage la brève récolte de baies.",
    "Berry drying mats|Sheltered berry racks|Warm-air drying cabinet|Berry drying house",
    "Nattes de séchage|Claies à baies abritées|Armoire à air chaud|Séchoir à baies",
    {
      biomes: ["tundra-heath"],
      climates: ["tundra", "cold", "arctic"],
      finishing: { cloth: 1 },
    },
  ),
  niche(
    "whale-blubber-cutting",
    "whaling",
    "any",
    ["oil"],
    "Blubber cutting yards",
    "Ateliers de découpe du lard de baleine",
    "Evenly cut blubber exposes more material to the rendering kettles and improves oil recovery from each landed whale.",
    "Le lard découpé régulièrement offre davantage de matière aux chaudières et améliore la récupération d’huile de chaque baleine débarquée.",
    "Blubber cutting benches|Raised cutting stages|Mechanical blubber slicer|Integrated cutting house",
    "Bancs de découpe du lard|Plateformes de découpe|Trancheuse mécanique|Atelier de découpe intégré",
    { coastal: true, finishing: { ore: 2 } },
  ),
];
