import type { SpecialistBranch } from "./infrastructure-specialists";
/** These branches have their own output or ecological role, not an additional
 * generic +yield layer. Recipes use craft-specific materials scaled to the local construction budget. */
export const PRACTICE_BRANCHES: readonly SpecialistBranch[] = [
  {
    id: "resin-tapping",
    track: "forestry",
    site: "forest",
    primary: false,
    effect: "yield",
    goods: ["oil"],
    name: "Conifer resin yards",
    fr: "Chantiers de résine",
    climates: ["cold", "alpine"],
    biomes: ["forest", "old-growth-forest", "woods"],
    description:
      "Shallow tapping cuts and collection cups gather resin from conifers during the warm growing season.",
    descriptionFr:
      "Des entailles peu profondes et des godets recueillent la résine des conifères pendant la saison chaude.",
    stages: [
      "Resin cups",
      "Managed tapping rounds",
      "Resin collection pumps",
      "Integrated resin yard",
    ],
    stagesFr: [
      "Godets à résine",
      "Tournées de gemmage",
      "Pompes de collecte",
      "Chantier résinier intégré",
    ],
    finishing: { ceramics: 2 },
  },
  {
    id: "woodland-mushrooms",
    track: "forestry",
    site: "forest",
    primary: false,
    effect: "yield",
    goods: ["grain"],
    name: "Woodland food gardens",
    fr: "Jardins nourriciers forestiers",
    climates: [
      "temperate",
      "oceanic",
      "temperate-rainforest",
      "cold",
      "alpine",
    ],
    description:
      "Shaded beds of fallen wood and leaf litter support an autumn mushroom harvest beneath the trees.",
    descriptionFr:
      "Des couches ombragées de bois tombé et de litière portent une récolte automnale de champignons sous les arbres.",
    stages: [
      "Shaded mushroom beds",
      "Managed woodland beds",
      "Spawn nursery",
      "Forest food nursery",
    ],
    stagesFr: [
      "Couches ombragées",
      "Couches forestières entretenues",
      "Pépinière de mycélium",
      "Pépinière nourricière",
    ],
    finishing: { lumber: 2, ceramics: 1 },
  },
  {
    id: "shellfish-beds",
    track: "fishery",
    site: "any",
    primary: false,
    effect: "yield",
    goods: ["fish"],
    name: "Coastal shellfish beds",
    fr: "Parcs à coquillages",
    coastal: true,
    waterways: ["coast", "shoal", "reef"],
    climates: [
      "temperate",
      "oceanic",
      "temperate-rainforest",
      "mediterranean",
      "subtropical",
      "tropical",
      "tropical-maritime",
      "monsoon",
      "mesoamerican",
    ],
    description:
      "Stakes, baskets and suspended ropes raise mussels and oysters in sheltered coastal water.",
    descriptionFr:
      "Des pieux, paniers et cordages suspendus élèvent moules et huîtres dans les eaux côtières abritées.",
    stages: [
      "Shellfish stakes",
      "Basket beds",
      "Suspended culture ropes",
      "Managed shellfish park",
    ],
    stagesFr: [
      "Pieux à coquillages",
      "Parcs de paniers",
      "Cordages de culture",
      "Parc conchylicole",
    ],
    finishing: { lumber: 2, wool: 1 },
  },
  {
    id: "spawning-reeds",
    track: "fishery",
    site: "any",
    primary: false,
    effect: "yield",
    goods: ["fish"],
    name: "Reed spawning refuges",
    fr: "Frayères de roseaux",
    waterways: ["river", "lake"],
    description:
      "Protected reed margins and quiet coves offer shelter for visiting fish along the freshwater shore.",
    descriptionFr:
      "Des roselières protégées et des anses calmes abritent les poissons de passage sur les rives d’eau douce.",
    stages: [
      "Protected reed margin",
      "Quiet spawning coves",
      "Managed reed nursery",
      "Connected spawning refuges",
    ],
    stagesFr: [
      "Roselière protégée",
      "Anses de frai",
      "Pépinière de roseaux",
      "Réseau de frayères",
    ],
    finishing: { lumber: 1, stone: 1 },
  },
  {
    id: "coppice-stools",
    track: "forestry",
    site: "forest",
    primary: false,
    effect: "yield",
    goods: ["lumber"],
    name: "Coppice rotations",
    fr: "Taillis en rotation",
    description:
      "Managed stools regrow slender poles between staggered winter cuts, complementing the mature timber harvest.",
    descriptionFr:
      "Des souches entretenues repoussent entre les coupes hivernales échelonnées, complétant la récolte de gros bois.",
    stages: [
      "Marked coppice stools",
      "Staggered coppice coupes",
      "Pole handling yard",
      "Coordinated coppice estate",
    ],
    stagesFr: [
      "Souches marquées",
      "Coupes échelonnées",
      "Chantier de perches",
      "Domaine de taillis organisé",
    ],
    biomes: ["woods", "river-woods"],
    climates: ["temperate", "oceanic", "mediterranean"],
  },
  {
    id: "river-pollards",
    track: "forestry",
    site: "forest",
    primary: false,
    effect: "yield",
    goods: ["lumber"],
    name: "Riverbank pollards",
    fr: "Têtards riverains",
    description:
      "Raised pollard crowns keep new shoots above browsing animals along watered banks. Winter pruning supplies usable poles.",
    descriptionFr:
      "Les couronnes élevées des arbres têtards protègent les rejets des animaux sur les rives humides. La taille hivernale fournit des perches.",
    stages: [
      "Marked pollard line",
      "Rotating crown cuts",
      "Bank-side pole yard",
      "Managed pollard corridor",
    ],
    stagesFr: [
      "Alignement marqué",
      "Tailles en rotation",
      "Chantier de perches riverain",
      "Corridor de têtards entretenu",
    ],
    biomes: ["river-woods", "woods"],
    climates: ["temperate", "oceanic"],
    freshwater: true,
  },
  {
    id: "heath-apiaries",
    track: "foraging",
    site: "any",
    primary: false,
    effect: "yield",
    goods: ["grain"],
    name: "Heath apiaries",
    fr: "Ruchers de lande",
    description:
      "Sheltered hives gather nectar during the short flowering season of the heath.",
    descriptionFr:
      "Des ruches abritées recueillent le nectar pendant la courte floraison de la lande.",
    stages: [
      "Sheltered skeps",
      "Flowering-ground apiary",
      "Honey extraction room",
      "Insulated honey house",
    ],
    stagesFr: [
      "Paniers abrités",
      "Rucher de floraison",
      "Salle d’extraction",
      "Miellerie isolée",
    ],
    biomes: ["tundra-heath"],
    climates: ["tundra"],
  },
  {
    id: "meadow-apiaries",
    track: "husbandry",
    site: "any",
    primary: false,
    effect: "yield",
    goods: ["grain"],
    name: "Meadow apiaries",
    fr: "Ruchers de prairie",
    description:
      "Flower-rich meadow margins support a summer honey harvest alongside the pasture.",
    descriptionFr:
      "Les bordures fleuries des prairies permettent une récolte estivale de miel en complément du pâturage.",
    stages: [
      "Meadow skeps",
      "Managed flower margins",
      "Framed hive yard",
      "Cooperative honey house",
    ],
    stagesFr: [
      "Paniers de prairie",
      "Bordures fleuries entretenues",
      "Rucher à cadres",
      "Miellerie collective",
    ],
    biomes: ["pasture", "coastal-pasture", "flood-meadow"],
    climates: ["temperate", "oceanic", "prairie", "mediterranean"],
  },
  {
    id: "paddy-ducks",
    track: "soil",
    site: "rice",
    primary: false,
    effect: "yield",
    goods: ["meat"],
    name: "Rice–duck husbandry",
    fr: "Élevage riz-canards",
    description:
      "Sheltered duck flocks forage in watered paddies, using insects and fallen grain during the rice season.",
    descriptionFr:
      "Des canards abrités se nourrissent dans les rizières en eau, profitant des insectes et du grain tombé pendant la saison rizicole.",
    stages: [
      "Duck shelter",
      "Guarded paddy runs",
      "Integrated duck yards",
      "Coordinated rice–duck holdings",
    ],
    stagesFr: [
      "Abri à canards",
      "Parcours gardés",
      "Cours d’élevage intégrées",
      "Exploitations riz-canards coordonnées",
    ],
    biomes: ["rice-field", "flood-rice"],
    climates: ["tropical", "subtropical", "monsoon", "mesoamerican"],
    freshwater: true,
  },
  {
    id: "woodland-pannage",
    track: "forestry",
    site: "forest",
    primary: false,
    effect: "yield",
    goods: ["meat"],
    name: "Woodland pannage",
    fr: "Glandée forestière",
    description:
      "Domestic pigs forage beneath mature broadleaved trees after the autumn mast falls, complementing timber and wild game.",
    descriptionFr:
      "Les porcs domestiques profitent des glands et faînes sous les feuillus adultes en automne, en complément du bois et du gibier.",
    stages: [
      "Woodland pig shelter",
      "Rotating mast enclosures",
      "Autumn holding yards",
      "Managed pannage woodland",
    ],
    stagesFr: [
      "Abri forestier à porcs",
      "Enclos de glandée en rotation",
      "Parcs automnaux",
      "Bois de glandée aménagé",
    ],
    biomes: ["woods", "old-growth-forest", "hunting-forest"],
    climates: ["temperate", "oceanic"],
  },
  {
    id: "seal-haulout-wardens",
    track: "hunting",
    site: "seal",
    effect: "yield",
    goods: ["hides"],
    name: "Seal haul-out wardens",
    fr: "Gardiens des reposoirs à phoques",
    description:
      "Quiet shore approaches and guarded resting grounds reduce disturbance around seal colonies while organizing the coastal hunt.",
    descriptionFr:
      "Des approches discrètes et des reposoirs gardés réduisent les perturbations des colonies tout en organisant la chasse côtière.",
    stages: [
      "Marked quiet shore",
      "Guarded haul-out grounds",
      "Coastal observation huts",
      "Managed seal refuge",
    ],
    stagesFr: [
      "Rivage calme balisé",
      "Reposoirs gardés",
      "Cabanes d’observation",
      "Refuge côtier aménagé",
    ],
    climates: ["arctic", "glacial", "tundra"],
    specialty: "refuge",
    coastal: true,
  },
  {
    id: "quarry-return-crates",
    track: "quarrying",
    site: "stone",
    primary: false,
    effect: "yield",
    goods: ["stone"],
    name: "Reusable stone cradles",
    fr: "Berceaux de pierre réutilisables",
    description:
      "Fitted timber cradles and reusable padding protect dressed stone and recover packing materials for later local works.",
    descriptionFr:
      "Des berceaux ajustés et des garnitures réutilisables protègent la pierre taillée et préservent les emballages pour les futurs ouvrages locaux.",
    stages: [
      "Fitted stone cradles",
      "Return packing yard",
      "Standard lifting cradles",
      "Integrated packing depot",
    ],
    stagesFr: [
      "Berceaux ajustés",
      "Chantier de retour",
      "Berceaux de levage standardisés",
      "Dépôt d’emballage intégré",
    ],
  },
];
