import type { Climate } from "./climate-content";
import type { Season } from "./seasons";
import type { SpecialistBranch } from "./infrastructure-specialists";
export interface RotationPattern {
  biomes: readonly string[];
  climates: readonly Climate[];
  seasons: readonly Season[];
  water?: boolean;
  drainage?: boolean;
  fertile?: boolean;
  maxElevation?: number;
  secondaryBiome: string;
}
// Small secondary plots/relay sowings, not a second full-field main harvest.
const rotation = (
  id: string,
  name: string,
  fr: string,
  description: string,
  descriptionFr: string,
  pattern: RotationPattern,
): SpecialistBranch => ({
  id: `rotation-${id}`,
  track: "soil",
  name,
  fr,
  description,
  descriptionFr,
  effect: "yield",
  site: "any",
  goods: ["grain"],
  rotation: pattern,
  stages: [
    `${name}: trial plots`,
    `${name}: seed nursery`,
    `${name}: sowing equipment`,
    `${name}: rotation station`,
  ],
  stagesFr: [
    `${fr} : parcelles d’essai`,
    `${fr} : pépinière de semences`,
    `${fr} : matériel de semis`,
    `${fr} : station de rotation`,
  ],
});
export const ROTATION_BRANCHES: readonly SpecialistBranch[] = [
  rotation(
    "stubble-turnips",
    "Stubble turnip rotation",
    "Rotation de navets sur chaumes",
    "Quick-growing turnips follow the summer cereal harvest on a small share of the field.",
    "Des navets à croissance rapide suivent la moisson d’été sur une petite part du champ.",
    {
      biomes: [
        "golden-fields",
        "barley-fields",
        "flood-wheat",
        "chernozem-wheat",
      ],
      climates: ["temperate", "oceanic", "mediterranean"],
      seasons: ["autumn"],
      secondaryBiome: "turnip-fields",
    },
  ),
  rotation(
    "atlantic-beans",
    "Atlantic overwintered beans",
    "Fèves hivernées atlantiques",
    "Sheltered, well-drained plots carry a small overwintered bean crop before the main cereal harvest.",
    "Des parcelles abritées et drainées portent une petite récolte de fèves avant la moisson principale.",
    {
      biomes: ["golden-fields", "barley-fields", "oat-fields", "flood-wheat"],
      climates: ["oceanic", "temperate-rainforest"],
      seasons: ["spring"],
      drainage: true,
      secondaryBiome: "turnip-fields",
    },
  ),
  rotation(
    "continental-lentils",
    "Continental relay lentils",
    "Lentilles dérobées continentales",
    "Short-season lentils use watered stubble plots after an early cereal harvest; autumn frost remains a risk.",
    "Des lentilles précoces utilisent des chaumes arrosés après la moisson ; le gel automnal reste un risque.",
    {
      biomes: ["golden-fields", "barley-fields", "chernozem-wheat"],
      climates: ["steppe", "prairie"],
      seasons: ["autumn"],
      water: true,
      maxElevation: 0.65,
      secondaryBiome: "turnip-fields",
    },
  ),
  rotation(
    "prairie-peas",
    "Prairie pea strips",
    "Bandes de pois des prairies",
    "Early peas occupy small irrigated strips ahead of the late oilseed harvest.",
    "Des pois précoces occupent de petites bandes irriguées avant la récolte tardive des oléagineux.",
    {
      biomes: ["sunflower-fields"],
      climates: ["prairie"],
      seasons: ["summer"],
      water: true,
      secondaryBiome: "turnip-fields",
    },
  ),
  rotation(
    "mediterranean-chickpeas",
    "Irrigated chickpea rotation",
    "Rotation de pois chiches irrigués",
    "A limited chickpea crop follows cereal harvesting where irrigation bridges the dry summer.",
    "Une petite culture de pois chiches suit la moisson là où l’irrigation compense l’été sec.",
    {
      biomes: ["golden-fields", "barley-fields", "flood-wheat"],
      climates: ["mediterranean", "subtropical"],
      seasons: ["autumn"],
      water: true,
      secondaryBiome: "millet-fields",
    },
  ),
  rotation(
    "olive-broadbeans",
    "Olive orchard broad beans",
    "Fèves entre les oliviers",
    "Winter rain supports broad beans between olive rows, giving a small spring food harvest.",
    "Les pluies hivernales nourrissent des fèves entre les oliviers, pour une petite récolte alimentaire au printemps.",
    {
      biomes: ["olive-grove"],
      climates: ["mediterranean"],
      seasons: ["spring"],
      maxElevation: 0.72,
      secondaryBiome: "turnip-fields",
    },
  ),
  rotation(
    "rice-winter-peas",
    "Rice and winter peas",
    "Riz et pois d’hiver",
    "Drained paddy margins carry cool-season peas after rice, harvested before the summer planting.",
    "Les bordures drainées des rizières portent des pois de saison fraîche, récoltés avant le semis estival.",
    {
      biomes: ["rice-field", "flood-rice"],
      climates: ["subtropical"],
      seasons: ["spring"],
      water: true,
      drainage: true,
      secondaryBiome: "turnip-fields",
    },
  ),
  rotation(
    "rice-mungbeans",
    "Rice and mung beans",
    "Riz et haricots mungo",
    "Brief warm fallows between rice crops support small mung-bean plots with controlled water and drainage.",
    "De courtes jachères chaudes entre les rizicultures accueillent des haricots mungo avec arrosage et drainage contrôlés.",
    {
      biomes: ["rice-field", "flood-rice"],
      climates: ["tropical", "tropical-maritime"],
      seasons: ["winter"],
      water: true,
      drainage: true,
      secondaryBiome: "millet-fields",
    },
  ),
  rotation(
    "monsoon-lentils",
    "Post-monsoon lentils",
    "Lentilles après mousson",
    "Lentils use residual moisture in drained alluvial rice ground after the monsoon harvest.",
    "Les lentilles utilisent l’humidité résiduelle des rizières alluviales drainées après la mousson.",
    {
      biomes: ["rice-field", "flood-rice"],
      climates: ["monsoon"],
      seasons: ["winter"],
      drainage: true,
      fertile: true,
      secondaryBiome: "millet-fields",
    },
  ),
  rotation(
    "desert-sorghum",
    "Alluvial wheat and sorghum",
    "Blé alluvial et sorgho",
    "Irrigated sorghum follows the spring wheat harvest in warm, fertile river soils.",
    "Du sorgho irrigué suit la récolte printanière du blé dans les terres fluviales chaudes et fertiles.",
    {
      biomes: ["flood-wheat"],
      climates: ["desert", "hyperarid", "semiarid"],
      seasons: ["autumn"],
      water: true,
      fertile: true,
      secondaryBiome: "sorghum-fields",
    },
  ),
  rotation(
    "oasis-beans",
    "Oasis understory beans",
    "Haricots sous les palmiers",
    "Small irrigated beds beneath the palms yield beans before the main date harvest.",
    "De petites planches irriguées sous les palmiers donnent des haricots avant la récolte des dattes.",
    {
      biomes: ["oasis"],
      climates: ["desert", "hyperarid", "semiarid"],
      seasons: ["spring"],
      water: true,
      secondaryBiome: "turnip-fields",
    },
  ),
  rotation(
    "millet-cowpeas",
    "Millet and cowpea strips",
    "Millet et bandes de niébé",
    "Watered cowpea strips supply a modest early harvest alongside late millet on warm lowland farms.",
    "Des bandes de niébé arrosées donnent une petite récolte précoce près du millet tardif des basses terres chaudes.",
    {
      biomes: ["millet-fields"],
      climates: ["semiarid", "savanna"],
      seasons: ["summer"],
      water: true,
      maxElevation: 0.65,
      secondaryBiome: "millet-fields",
    },
  ),
  rotation(
    "savanna-pulses",
    "Savanna relay pulses",
    "Légumineuses dérobées de savane",
    "Fertile plots carry short-season pulses before the late sorghum harvest, supported by stored water.",
    "Des parcelles fertiles portent des légumineuses précoces avant le sorgho tardif, avec une réserve d’eau.",
    {
      biomes: ["sorghum-fields", "flood-sorghum"],
      climates: ["savanna", "semiarid"],
      seasons: ["summer"],
      water: true,
      fertile: true,
      secondaryBiome: "millet-fields",
    },
  ),
  rotation(
    "maize-relay-beans",
    "Maize relay beans",
    "Haricots dérobés du maïs",
    "Small bean plots share the warm growing season with maize, supplying food before the main autumn harvest.",
    "De petites parcelles de haricots partagent la saison chaude avec le maïs et fournissent de la nourriture avant l’automne.",
    {
      biomes: ["maize-field"],
      climates: ["mesoamerican"],
      seasons: ["summer"],
      fertile: true,
      maxElevation: 0.65,
      secondaryBiome: "turnip-fields",
    },
  ),
  rotation(
    "maize-squash",
    "Lowland maize and squash",
    "Maïs et courges des basses terres",
    "A small early squash planting uses irrigated, well-drained lowland plots before the main maize crop.",
    "De petites plantations précoces de courges utilisent des terres basses irriguées et drainées avant le maïs.",
    {
      biomes: ["maize-field", "chinampa-gardens"],
      climates: ["mesoamerican"],
      seasons: ["spring"],
      water: true,
      drainage: true,
      maxElevation: 0.52,
      secondaryBiome: "potato-fields",
    },
  ),
  rotation(
    "valley-potato-quinoa",
    "Valley potato and quinoa greens",
    "Pommes de terre et feuilles de quinoa",
    "Sheltered valley plots provide young quinoa leaves in spring before the later potato harvest.",
    "Des parcelles de vallée abritées fournissent de jeunes feuilles de quinoa au printemps avant les récoltes de pommes de terre.",
    {
      biomes: ["potato-fields"],
      climates: ["andean"],
      seasons: ["spring"],
      water: true,
      fertile: true,
      maxElevation: 0.52,
      secondaryBiome: "barley-fields",
    },
  ),
];
